# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-04 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20190704_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='/MainApp/media/images/'),
        ),
    ]
