# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-04 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20190704_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='/Users/gustavo/Documents/Coding Random Stuff/PyTestApp/main/apps/MainApp/media/images/'),
        ),
    ]
